HospitalSystem.Web/Controllers/EmployeeController.cs
using HospitalSystem.Data.Data;
using HospitalSystem.Entities.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalSystem.Web.Controllers
{
    public class EmployeeController : Controller
    {
        ApplicationDbContext _db;

        public EmployeeController()
        {
            _db = new ApplicationDbContext();
        }

        public ActionResult Index(int page = 1)
        {
            using (_db = new ApplicationDbContext())
            {
                var employee = _db.Employees.Include("EmployeeInformation").Include("Title").Include("Gender").Where(i => i.IsDeleted == false && i.IsConfirm == true).OrderByDescending(i => i.CreatedDate).ToPagedList(page, 25);
                return View(employee);
            }
        }

        public ActionResult Detail(int id)
        {
            return View(_db.Employees.Find(id));
        }

        public ActionResult Create()
        {
            ViewBag.Titles = _db.Titles.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            ViewBag.Genders = _db.Genders.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employee model, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                image.SaveAs(Server.MapPath("~/img/employee/" + image.FileName));
                model.Photo = image.FileName;
            }
            _db.Employees.Add(model);
            _db.Entry(model).State = EntityState.Added;
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Titles = _db.Titles.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            ViewBag.Genders = _db.Genders.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            using (_db=new ApplicationDbContext())
            {
                var editEmployee = _db.Employees.Where(i => i.Id == id).FirstOrDefault();
                if (editEmployee!=null)
                {
                    return View(editEmployee);
                }
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Employee model, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                image.SaveAs(Server.MapPath("~/img/employee/" + image.FileName));
                model.Photo = image.FileName;
            }
            _db.Employees.Attach(model);
            _db.Entry(model).State = EntityState.Modified;
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            using (_db = new ApplicationDbContext())
            {
                var deleteEmployee = _db.Employees.Find(id);
                if (deleteEmployee!=null)
                {
                    _db.Employees.Remove(deleteEmployee);
                    _db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
    }
}

HospitalSystem.Web/Views/Employee/Create.cshtml
@model HospitalSystem.Entities.Models.Employee
@{
    ViewBag.Title = "Yeni Çalışan Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="" enctype="multipart/form-data">
                                    @using (Html.BeginForm("Create", "Employee", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()                                        
                                        <h4><label class="label label-primary">Çalışan Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Adı-Soyadı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NameSurname" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kimlik Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="IdentityNo" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Doğum Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Birthdate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Cinsiyeti: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.GenderId, new SelectList(ViewBag.Genders, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.GenderId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Başlama Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Hiredate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ünvanı: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.TitleId, new SelectList(ViewBag.Titles, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.TitleId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>  
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Resim</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="image" type="file" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Doktor İletişim Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Eyalet/Bölge</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.Province" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Şehir</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.City" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ülke</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.Country" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mail Adresi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.EMail" type="email" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.PhoneNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ev Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.HomeNumber" type="text" required />
                                            </div>
                                        </div>                                        
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Çalışanı Ekle</button>
                                                <a href="~/Employee/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Employee/Detail.cshtml
@model HospitalSystem.Entities.Models.Employee
@{
    ViewBag.Title = "Çalışan İletşim Bilgisi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/Employee/Index" class="btn btn-primary">Çalışan Listesi</a> || <a href="~/Employee/Delete/@Model.Id" class="btn btn-danger">Doktoru Sil</a>
                        </header>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Eyalet/Bölge</th>
                                    <th>Şehir</th>
                                    <th>Ülke</th>
                                    <th>Mail Adresi</th>
                                    <th>Telefon No</th>
                                    <th>Ev Telefon No</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>@Model.EmployeeInformation.Province</td>
                                    <td>@Model.EmployeeInformation.City</td>
                                    <td>@Model.EmployeeInformation.Country</td>
                                    <td>@Model.EmployeeInformation.EMail</td>
                                    <td>@Model.EmployeeInformation.PhoneNumber</td>
                                    <td>@Model.EmployeeInformation.HomeNumber</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Employee/Edit.cshtml
@model HospitalSystem.Entities.Models.Employee
@{
    ViewBag.Title = "Çalışanı Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="" enctype="multipart/form-data">
                                    @using (Html.BeginForm("Edit", "Employee", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <h4><label class="label label-primary">Çalışan Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Adı-Soyadı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NameSurname" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kimlik Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="IdentityNo" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Doğum Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Birthdate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Cinsiyeti: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.GenderId, new SelectList(ViewBag.Genders, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.GenderId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Başlama Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Hiredate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ünvanı: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.TitleId, new SelectList(ViewBag.Titles, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.TitleId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Resim</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="image" type="file" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Doktor İletişim Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Eyalet/Bölge</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.Province" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Şehir</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.City" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ülke</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.Country" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mail Adresi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.EMail" type="email" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.PhoneNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ev Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="EmployeeInformation.HomeNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Güncelleme Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="UpdatedDate" type="datetime" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Çalışan Bilgilerini Güncelle</button>
                                                <a href="~/Employee/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Employee/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<HospitalSystem.Entities.Models.Employee>
@{
    ViewBag.Title = "Hastane Çalışan Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        @ViewBag.Title || <a href="~/Employee/Create" class="btn btn-primary btn-xs">Yeni Çalışan Ekle</a>  || <a href="~/ConfirmList/EmployeeConfirmList" class="btn btn-warning btn-xs">Çalışan Onay Listesi</a>
                    </header>
                    <div class="panel-body">
                        <div class="adv-table">
                            <table class="display table table-bordered table-striped" id="example">
                                <thead>
                                    <tr>
                                        <th width="90">Resim</th>
                                        <th>Adı-Soyadı</th>
                                        <th>Kimlik No</th>
                                        <th>Doğum Tarihi - Başlama Tarihi</th>
                                        <th>Cinsiyeti - Title</th>
                                        <th>Eklenme Tarihi</th>
                                        <th>Güncellenme Tarihi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="gradeX">
                                            <td width="90"><img src="~/img/employee/@item.Photo" class="img-responsive" /></td>
                                            <td>@item.NameSurname</td>
                                            <td>@item.IdentityNo</td>
                                            <td>@item.Birthdate.ToShortDateString() - @item.Hiredate.ToShortDateString()</td>
                                            <td>@item.Gender.Name - @item.Title.Name</td>
                                            <td>@item.CreatedDate.ToShortDateString()</td>
                                            <td>
                                                @if (item.UpdatedDate != null)
                                                {
                                                    @item.UpdatedDate.Value.ToShortDateString()
                                                }
                                                else
                                                {
                                                }
                                            </td>
                                            <td>
                                                <a href="~/Employee/Edit/@item.Id" class="btn btn-success btn-xs">Güncelle</a>
                                                <a href="~/Employee/Detail/@item.Id" class="btn btn-info btn-xs">Detay</a>
                                                <a href="~/Employee/Delete/@item.Id" class="btn btn-danger btn-xs">Sil</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th width="90">Resim</th>
                                        <th>Adı-Soyadı</th>
                                        <th>Kimlik No</th>
                                        <th>Doğum Tarihi - Başlama Tarihi</th>
                                        <th>Cinsiyeti - Title</th>
                                        <th>Eklenme Tarihi</th>
                                        <th>Güncellenme Tarihi</th>
                                    </tr>
                                </tfoot>
                            </table>
                            <div class="pagination">
                                <div class="paginate_active">
                                    @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>
</section>