HospitalSystem.Web/Controllers/NurseController.cs
using HospitalSystem.Data.Data;
using HospitalSystem.Entities.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalSystem.Web.Controllers
{
    public class NurseController : Controller
    {
        ApplicationDbContext _db;

        public NurseController()
        {
            _db = new ApplicationDbContext();
        }

        public ActionResult Index(int page = 1)
        {
            using (_db = new ApplicationDbContext())
            {
                var nurseList = _db.Nurses.Include("Gender").Include("NurseInformation").Include("NurseDegree").Include("Departman").Where(i => i.IsDeleted == false && i.IsConfirm == true).OrderByDescending(i => i.Hiredate).ToPagedList(page, 25);
                return View(nurseList);
            }
        }

        public ActionResult Detail(int id)
        {
            return View(_db.Nurses.Find(id));
        }

        public ActionResult NurseInfo(int id)
        {
            var information = _db.Nurses.Where(i => i.NurseInformationId == id).FirstOrDefault();
            return View(information);
        }

        public ActionResult NurseDetail(int id)
        {
            var detail = _db.Nurses.Where(i => i.NurseDegreeId == id).FirstOrDefault();
            return View(detail);
        }

        public ActionResult Create()
        {
            ViewBag.Departmans = _db.Departmans.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            ViewBag.Genders = _db.Genders.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Nurse model, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                image.SaveAs(Server.MapPath("~/img/nurse/" + image.FileName));
                model.Photo = image.FileName;
            }
            _db.Nurses.Add(model);
            _db.Entry(model).State = EntityState.Added;
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Departmans = _db.Departmans.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            ViewBag.Genders = _db.Genders.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            using (_db = new ApplicationDbContext())
            {
                var editNurse = _db.Nurses.Where(i => i.Id == id).FirstOrDefault();
                if (editNurse != null)
                {
                    return View(editNurse);
                }
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Nurse model, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                image.SaveAs(Server.MapPath("~/img/nurse/" + image.FileName));
                model.Photo = image.FileName;
            }
            _db.Nurses.Attach(model);
            _db.Entry(model).State = EntityState.Modified;
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            using (_db = new ApplicationDbContext())
            {
                var deleteNurse = _db.Nurses.Find(id);
                if (deleteNurse != null)
                {
                    _db.Nurses.Remove(deleteNurse);
                    _db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
    }
}

HospitalSystem.Web/Views/Nurse/Create.cshtml
@model HospitalSystem.Entities.Models.Nurse
@{
    ViewBag.Title = "Yeni Hemşire Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="" enctype="multipart/form-data">
                                    @using (Html.BeginForm("Create", "Nurse", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <h4><label class="label label-primary">Hemşirenin Bölümü</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Bölüm Listesi: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.DepartmanId, new SelectList(ViewBag.Departmans, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.DepartmanId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hemşire Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Adı-Soyadı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NameSurname" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kimlik Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="IdentityNo" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Doğum Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Birthdate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Cinsiyeti: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.GenderId, new SelectList(ViewBag.Genders, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.GenderId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Resim</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="image" type="file" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Başlama Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Hiredate" type="datetime" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hemşire İletişim Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Eyalet/Bölge</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.Province" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Şehir</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.City" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ülke</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.Country" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mail Adresi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.EMail" type="email" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.PhoneNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ev Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.HomeNumber" type="text" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Doktor Lisans Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Üniversite Adı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseDegree.Universirt" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Lisans Derecesi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseDegree.Degree" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mezuniyet Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseDegree.Date" type="datetime" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Hemşireyi Ekle</button>
                                                <a href="~/Nurse/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Nurse/Detail.cshtml
@model HospitalSystem.Entities.Models.Nurse
@{
    ViewBag.Title = "Hemşire Detay Bilgileri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/Nurse/Index" class="btn btn-primary">Hemşire Listesi</a> || <a href="~/Nurse/Delete/@Model.Id" class="btn btn-danger">Hemşireyi Sil</a>
                        </header>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Cinsiyeti</th>
                                    <th>Bölümü</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>@Model.Gender.Name</td>
                                    <td>@Model.Departman.Name</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Nurse/Edit.cshtml
@model HospitalSystem.Entities.Models.Nurse
@{
    ViewBag.Title = "Hemşire Bilgisini Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="" enctype="multipart/form-data">
                                    @using (Html.BeginForm("Create", "Nurse", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <h4><label class="label label-primary">Hemşirenin Bölümü</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Bölüm Listesi: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.DepartmanId, new SelectList(ViewBag.Departmans, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.DepartmanId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hemşire Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Adı-Soyadı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NameSurname" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kimlik Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="IdentityNo" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Doğum Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Birthdate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Cinsiyeti: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.GenderId, new SelectList(ViewBag.Genders, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.GenderId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Resim</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="image" type="file" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Başlama Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Hiredate" type="datetime" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hemşire İletişim Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Eyalet/Bölge</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.Province" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Şehir</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.City" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ülke</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.Country" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mail Adresi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.EMail" type="email" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.PhoneNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ev Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseInformation.HomeNumber" type="text" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Doktor Lisans Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Üniversite Adı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseDegree.Universirt" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Lisans Derecesi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseDegree.Degree" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mezuniyet Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NurseDegree.Date" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Güncelleme Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="UpdatedDate" type="datetime" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Hemşireyi Güncelle</button>
                                                <a href="~/Nurse/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Nurse/NurseDetail.cshtml
@model HospitalSystem.Entities.Models.Nurse
@{
    ViewBag.Title = "Hemşire Lisans Bilgileri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/Nurse/Index" class="btn btn-primary">Hemşire Listesi</a> || <a href="~/Nurse/Delete/@Model.Id" class="btn btn-danger">Hemşireyi Sil</a>
                        </header>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Üniversite Adı</th>
                                    <th>Bitirme Derecesi</th>
                                    <th>Mezuniyet Tarihi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>@Model.NurseDegree.University</td>
                                    <td>@Model.NurseDegree.Degree</td>
                                    <td>@Model.NurseDegree.Date.ToShortDateString()</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Nurse/NurseInfo.cshtml
@model HospitalSystem.Entities.Models.Nurse
@{
    ViewBag.Title = "Hemşire İletişim Bilgileri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/Nurse/Index" class="btn btn-primary">Hemşire Listesi</a> || <a href="~/Nurse/Delete/@Model.Id" class="btn btn-danger">Hemşireyi Sil</a>
                        </header>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Eyalet/Bölge</th>
                                    <th>Şehir</th>
                                    <th>Ülke</th>
                                    <th>Mail Adresi</th>
                                    <th>Telefon No</th>
                                    <th>Ev Telefon No</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>@Model.NurseInformation.Province</td>
                                    <td>@Model.NurseInformation.City</td>
                                    <td>@Model.NurseInformation.Country</td>
                                    <td>@Model.NurseInformation.EMail</td>
                                    <td>@Model.NurseInformation.PhoneNumber</td>
                                    <td>@Model.NurseInformation.HomeNumber</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>