HospitalSystem.Web/Controllers/PatientController.cs
using HospitalSystem.Data.Data;
using HospitalSystem.Entities.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalSystem.Web.Controllers
{
    public class PatientController : Controller
    {
        ApplicationDbContext _db;

        public PatientController()
        {
            _db = new ApplicationDbContext();
        }

        public ActionResult Index(int page = 1)
        {
            using (_db=new ApplicationDbContext())
            {
                var patient = _db.Patients.Include("PatientRooms").Include("Departman").Include("Appointment").Where(i => i.IsDeleted == false && i.IsConfirm == true).OrderByDescending(i => i.CreatedDate).ToPagedList(page, 25);
                return View(patient);
            }
        }

        public ActionResult Detail(int id)
        {
            var information = _db.Patients.Where(i => i.PatientInformationId == id).FirstOrDefault();
            return View(information);
        }

        public ActionResult CreatePatientRoom(int? id)
        {
            Session["patientID"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePatientRoom(PatientRoom model)
        {
            if (ModelState.IsValid)
            {
                model.PatientId = Convert.ToInt32(Session["patientID"]);
                using (_db=new ApplicationDbContext())
                {
                    _db.PatientRooms.Add(model);
                    _db.Entry(model).State = EntityState.Added;
                    _db.SaveChanges();
                }
            }
            return RedirectToAction("Index","PatientRoom");
        }

        public ActionResult EditPatientRoom(int id)
        {
            Session["patientID"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPatientRoom(PatientRoom model)
        {
            if (ModelState.IsValid)
            {
                model.PatientId = Convert.ToInt32(Session["patientID"]);
                using (_db = new ApplicationDbContext())
                {
                    _db.PatientRooms.Attach(model);
                    _db.Entry(model).State = EntityState.Modified;
                    _db.SaveChanges();
                }
            }
            return RedirectToAction("Index", "PatientRoom");
        }

        public ActionResult Create()
        {
            ViewBag.Genders = _db.Genders.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            ViewBag.Departmans = _db.Departmans.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Patient model)
        {
            if (ModelState.IsValid)
            {
                using (_db=new ApplicationDbContext())
                {
                    _db.Patients.Add(model);
                    _db.Entry(model).State = EntityState.Added;
                    _db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Genders = _db.Genders.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            ViewBag.Departmans = _db.Departmans.Where(i => i.IsDeleted == false).OrderBy(i => i.Name).ToList();
            using (_db=new ApplicationDbContext())
            {
                var editPatient = _db.Patients.Where(i => i.Id == id).FirstOrDefault();
                if (editPatient!=null)
                {
                    return View(editPatient);
                }
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Patient model)
        {
            if (ModelState.IsValid)
            {
                using (_db = new ApplicationDbContext())
                {
                    _db.Patients.Attach(model);
                    _db.Entry(model).State = EntityState.Modified;
                    _db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            using (_db=new ApplicationDbContext())
            {
                var deletePatient = _db.Patients.Find(id);
                if (deletePatient!=null)
                {
                    _db.Patients.Remove(deletePatient);
                    _db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
    }
}

HospitalSystem.Web/Views/Patient/Create.cshtml
@model HospitalSystem.Entities.Models.Patient
@{
    ViewBag.Title = "Yeni Hasta Kaydet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="">
                                    @using (Html.BeginForm("Create", "Patient", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <h4><label class="label label-primary">Hemşirenin Bölümü</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Bölüm Listesi: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.DepartmanId, new SelectList(ViewBag.Departmans, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.DepartmanId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hasta Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Adı-Soyadı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NameSurname" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kimlik Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="IdentityNo" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Doğum Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Birthdate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Cinsiyeti: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.GenderId, new SelectList(ViewBag.Genders, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.GenderId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hasta İletişim Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Eyalet/Bölge</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.Province" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Şehir</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.City" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ülke</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.Country" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mail Adresi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.EMail" type="email" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.PhoneNumber" type="text" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Hastayı Kaydet</button>
                                                <a href="~/Patient/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Patient/CreatePatientRoom.cshtml
@model HospitalSystem.Entities.Models.PatientRoom
@{
    ViewBag.Title = "Hastaya Oda Ata";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="">
                                    @using (Html.BeginForm("CreatePatientRoom", "Patient", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kat Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="FloorNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Oda Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="RoomNumber" type="text" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Odayı Ata</button>
                                                <a href="~/Patient/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Patient/Detail.cshtml
@model HospitalSystem.Entities.Models.Patient
@{
    ViewBag.Title = "Hasta İletişim Bilgileri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title || <a href="~/Patient/Index" class="btn btn-primary">Hasta Listesi</a> || <a href="~/Patient/Delete/@Model.Id" class="btn btn-danger">Hastayı Sil</a>
                        </header>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Eyalet/Bölge</th>
                                    <th>Şehir</th>
                                    <th>Ülke</th>
                                    <th>Mail Adresi</th>
                                    <th>Telefon No</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>@Model.PatientInformation.Province</td>
                                    <td>@Model.PatientInformation.City</td>
                                    <td>@Model.PatientInformation.Country</td>
                                    <td>@Model.PatientInformation.EMail</td>
                                    <td>@Model.PatientInformation.PhoneNumber</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Patient/Edit.cshtml
@model HospitalSystem.Entities.Models.Patient
@{
    ViewBag.Title = "Hasta Bilgilerini Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="">
                                    @using (Html.BeginForm("Create", "Patient", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <h4><label class="label label-primary">Hemşirenin Bölümü</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Bölüm Listesi: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.DepartmanId, new SelectList(ViewBag.Departmans, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.DepartmanId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hasta Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Adı-Soyadı</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="NameSurname" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kimlik Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="IdentityNo" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Doğum Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="Birthdate" type="datetime" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Cinsiyeti: *</label>
                                            <div class="col-lg-10">
                                                @Html.DropDownListFor(i => i.GenderId, new SelectList(ViewBag.Genders, "Id", "Name", new { @class = "form-control" }))
                                                @Html.ValidationMessageFor(i => i.GenderId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <hr />
                                        <h4><label class="label label-primary">Hasta İletişim Bilgileri</label></h4>
                                        <hr />
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Eyalet/Bölge</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.Province" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Şehir</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.City" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Ülke</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.Country" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Mail Adresi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.EMail" type="email" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Telefon No</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="PatientInformation.PhoneNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Güncelleme Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="UpdatedDate" type="datetime" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Hastayı Bilgilerini Güncelle</button>
                                                <a href="~/Patient/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>

HospitalSystem.Web/Views/Patient/EditPatientRoom.cshtml
@model HospitalSystem.Entities.Models.Patient
@{
    ViewBag.Title = "Hasta Odasını Gücelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="container" class="">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            @ViewBag.Title
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="">
                                    @using (Html.BeginForm("EditPatientRoom", "Patient", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Kat Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="FloorNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Oda Numarası</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="RoomNumber" type="text" required />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="firstname" class="control-label col-lg-2">Güncelleme Tarihi</label>
                                            <div class="col-lg-10">
                                                <input class=" form-control" id="firstname" name="UpdatedDate" type="datetime" required />
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-primary" type="submit">Odayı Güncelle</button>
                                                <a href="~/Patient/Index"><button class="btn btn-danger" type="button">İptal Et</button></a>
                                            </div>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </section>
</section>